.*: Assembler messages:
.*: Error: illegal operands `vsm4k.vi x1,v2,1'
.*: Error: illegal operands `vsm4k.vi v1,x2,1'
.*: Error: illegal operands `vsm4r.vs x1,v2'
.*: Error: illegal operands `vsm4r.vs v1,x2'
.*: Error: illegal operands `vsm4r.vv x1,v2'
.*: Error: illegal operands `vsm4r.vv v1,x2'
.*: Error: bad value for vector immediate field, value must be 0...31
.*: Error: bad value for vector immediate field, value must be 0...31
