.*: Assembler messages:
.*: Error: illegal operands `vsm3c.vi x1,v2,1'
.*: Error: illegal operands `vsm3c.vi v1,x2,1'
.*: Error: illegal operands `vsm3me.vv x1,v2,v3'
.*: Error: illegal operands `vsm3me.vv v1,x2,v3'
.*: Error: illegal operands `vsm3me.vv v1,v2,x3'
.*: Error: bad value for vector immediate field, value must be 0...31
.*: Error: bad value for vector immediate field, value must be 0...31
